appname = comisiones_crud
httpport = ${COMISIONES_CRUD_HTTPPORT||8080}
runmode = ${COMISIONES_CRUD_RUNMODE||dev}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}
PGuser = ${COMISIONES_CRUD_DB_PGUSER}
PGpass = ${COMISIONES_CRUD_DB_PGPASS}
PGhost = ${COMISIONES_CRUD_DB_PGHOST}
PGport = ${COMISIONES_CRUD_DB_PGPORT}
PGdb = ${COMISIONES_CRUD_DB_PGDB}
PGschema = ${COMISIONES_CRUD_DB_PGSCHEMA}
