appname = comisiones_estudio_crud
httpport = 8080
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
#sqlconn = postgres://postgres:1234@192.168.160.1:5432/comisiones?sslmode=disable&search_path=comisiones

PGuser = ${COMISIONES_CRUD_V2_PGUSER}
PGpass = ${COMISIONES_CRUD_V2_PGPASS}
PGhost = ${COMISIONES_CRUD_V2_PGHOST}
PGport = ${COMISIONES_CRUD_V2_PGPORT}
PGdb = ${COMISIONES_CRUD_V2_PGDB}
PGschema = ${COMISIONES_CRUD_V2_PGSCHEMA}
